name: Trigger auto deployment for containerapp-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp-demo-AutoDeployTrigger-3f57f878-b3c2-4926-b2ab-cd12c11fba2d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: haojiehanglaxregistry.azurecr.io
          username: ${{ secrets.CONTAINERAPPDEMO_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPDEMO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: haojiehanglaxregistry.azurecr.io/containerapp-demo:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINERAPPDEMO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n containerapp-demo -g haojiehang --server haojiehanglaxregistry.azurecr.io --username  ${{ secrets.CONTAINERAPPDEMO_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPDEMO_REGISTRY_PASSWORD }}
            az containerapp update -n containerapp-demo -g haojiehang --image haojiehanglaxregistry.azurecr.io/containerapp-demo:${{ github.sha }}
